### ISSUE TITLE
RangeError : Invalid typed array length 

### ISSUE THREAD

**Issue by Alex-TRS** [iNViTiON/GoPro-Tagging#1]
WIth a long GoPro video (3.5gb) the script fails on any of the parts with the following error : 
buffer.js:11
    super(arg1, arg2, arg3);
    ^

RangeError: Invalid typed array length
    at Buffer.Uint8Array (native)
    at FastBuffer (buffer.js:11:5)
    at createUnsafeBuffer (buffer.js:38:12)
    at allocate (buffer.js:181:12)
    at Function.Buffer.allocUnsafe (buffer.js:141:10)
    at tryCreateBuffer (fs.js:474:21)
    at Object.fs.readFileSync (fs.js:519:14)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\gopro-tagging\gopro-tagging.js:5:74
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by iNViTiON** [comment]
I'm sorry but I don't have GoPro 4 anymore. Only GoPro 3 Black here and it didn't support HiLight tag.
Can you provide me a problem video file for me?

Thank you.

**Comment by Alex-TRS** [comment]
I can send you a link to one but its 3.5GB is that ok? I could try different lengths to find a smaller file with the problem if it is too big.
Here is the link for the 3.5gb file : https://goo.gl/48hHFx

Really nice of you to try and help by the way! I am a programmer but you'll find the issue must faster than I since it is your libraries :)

**Comment by iNViTiON** [comment]
That file ok for me. I start download it but I'm not sure when I will have time to check it out.

**Comment by Alex-TRS** [comment]
No worries thanks again! Let me know if I can help in any way.

**Comment by iNViTiON** [comment]
@Alex-TRS Sorry for this late response. As you can see I open issue in codem-isoboxer. The thing was this has a big problem than I think. I will try to figure out what I can do with it. But this should take a long time with my time.

**Comment by Alex-TRS** [comment]
No problem I have an alternative workflow for the time being. Its nice of you to try and fix it! Would be extremely time saving once the script works. Will keep following this issue. Thanks again
